In [2]:
class MyStandardScaler :
    def __init__(self):
        self.mean=None
        self.std = None
    def fit(self , X ):
        self.mean = X.mean()
        self.std = X.std()
        return self 
    def transform(self,X):
        return (X-self.mean)/self.std
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

In [12]:
import numpy as np 
X = np.array([[2,43,6,7,9],[3,4,56,3,2]])
scaler = MyStandardScaler()
print(scaler.fit_transform(X))
print(scaler.fit(X))
print(scaler.fit(X).mean)
print(scaler.fit(X).std)
print(scaler.transform(X))

[[-0.62639845  1.6068482  -0.40852073 -0.3540513  -0.24511244]
 [-0.57192902 -0.51745959  2.31495079 -0.57192902 -0.62639845]]
13.5
18.35892153695309
[[-0.62639845  1.6068482  -0.40852073 -0.3540513  -0.24511244]
 [-0.57192902 -0.51745959  2.31495079 -0.57192902 -0.62639845]]


In [15]:
import numpy as np 
import pandas as pd 

In [ ]:
# Input validation -> isinstance 
class MyStandardScaler :
    def __init__(self):
        self.mean=None
        self.std = None
    def fit(self , X ):
        # Checking whether X is a NumPy array or a DataFrame
        is_numpy = isinstance(X,np.ndarray)
        is_dataframe = isinstance(X,pd.DataFrame)
        if not(is_numpy or is_dataframe):
            raise TypeError(
                "Input must be a Numpy array or Pandas DataFrame"
            )
        if is_numpy:
            self.mean = X.mean(axis=0)
            self.std = X.std(axis=0)
        else :
            self.mean = X.mean()
            self.std = X.std()
        return self 
    def transform(self,X):
        if self.mean is None or self.std is None:
            raise ValueError(
                "Call fit() before transform()."
            ) 
        return (X-self.mean)/self.std 
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

In [ ]:
# Scaled value is diff for numpy and pandas as numpy used population standard deviation and pandas 
# used sample standard deviation ( we can make it same by making ddof => Deltas degree of freedom = 0)
person_data1 = np.array([[23,40000],[30,100000],[50,1000000]])
person_data2 = pd.DataFrame({
    'Age':[23,30,50],
    'Salary':[40000,100000,1000000]
    })
scaler1= MyStandardScaler()
scaler2 = MyStandardScaler()
print(scaler1.fit(person_data1).mean)
print(scaler1.fit_transform(person_data1))
print(scaler2.fit(person_data2).mean)
print(scaler2.fit_transform(person_data2))


[3.43333333e+01 3.80000000e+05]
[[-0.99061813 -0.77432878]
 [-0.37876576 -0.63768253]
 [ 1.36938388  1.41201131]]
Age           34.333333
Salary    380000.000000
dtype: float64
        Age    Salary
0 -0.808836 -0.632237
1 -0.309261 -0.520666
2  1.118097  1.152902
